version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: ${DB_NAME:-dbsymf}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${DB_NAME:-sqluser}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${DB_PASSWORD:-mood001}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    volumes:
      - db-data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###< doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###